import { Router } from "express";
import masterRoute from "./master.route";
import adminRoute from "./admin.route";
import countryRoute from "./country.route";
import companyRoute from "./company.route";
import stockRoute from "./stock.route";
import staticPageRoute from "./static-page.route";
import memoRoute from "./memo.route";
import invoiceRoute from "./invoice.route";
import conciergeRoute from "./concierge.route";
import wishlistRoute from "./wishlist-admin.route";
import cartAdminRoute from "./cart-admin.route";
import inquiryRoute from "./inquiry.route";
import currencyRoute from "./currency.route";
import homePageRoute from "./home-page.route";
import blogRoute from "./blog.route";
import packetRoute from "./packet.route";
import apiRoute from "./api.route";
import stockTransferRoute from "./stock-transfer.route";

export default function adminRouter() {
  const app = Router();
  masterRoute(app);
  adminRoute(app);
  countryRoute(app);
  companyRoute(app);
  stockRoute(app);
  staticPageRoute(app);
  memoRoute(app);
  invoiceRoute(app);
  conciergeRoute(app);
  wishlistRoute(app);
  cartAdminRoute(app);
  inquiryRoute(app);
  currencyRoute(app);
  homePageRoute(app);
  blogRoute(app);
  packetRoute(app);
  apiRoute(app);
  stockTransferRoute(app);
  return app;
}
