import { fieldFloatChain, fieldIntegerChain, fieldIntegerNotReqChain, fieldStringChain, fieldStringNotReqChain } from "../common-validation-rules";

export const addStockRules = [
    fieldStringChain("Stock Id", "stock_id"),
    fieldStringChain("Status", "status"),
    fieldFloatChain("weight", "weight"),
    fieldFloatChain("rate", "rate"),
    fieldFloatChain("Table value", "table_value"),
    fieldFloatChain("Depth value", "depth_value"),
    fieldFloatChain("measurement height", "measurement_height"),
    fieldFloatChain("measurement width", "measurement_width"),
    fieldFloatChain("measurement depth", "measurement_depth"),
    fieldStringNotReqChain("Local Location", "local_location"),
    fieldStringChain("video", "video"),
    fieldStringChain("image", "image"),
    fieldStringChain("certificate", "certificate"),
    fieldStringChain("ratio", "ratio"),
    fieldStringNotReqChain("User comments", "user_comments"),
    fieldStringNotReqChain("Admin comments", "admin_comments"),
    fieldIntegerChain("shape", "shape"),
    fieldIntegerChain("quantity", "quantity"),
    fieldIntegerChain("color", "color"),
    fieldIntegerChain("color_intensity", "color_intensity"),
    fieldIntegerChain("clarity", "clarity"),
    fieldIntegerChain("lab", "lab"),
    fieldIntegerChain("report", "report"),
    fieldIntegerChain("polish", "polish"),
    fieldIntegerChain("symmetry", "symmetry"),
    fieldIntegerChain("company", "company_id"),
    fieldIntegerNotReqChain("fluorescence", "fluorescence"),
]