import { fieldFloatChain, fieldFloatNotReqChain, fieldIntegerChain, fieldIntegerNotReqChain, fieldStringChain, fieldStringNotReqChain } from "../common-validation-rules";

export const addStockRules = [
    fieldStringChain("Stock Id", "stock_id"),
    fieldFloatChain("weight", "weight"),
    fieldFloatChain("rate", "rate"),
    fieldIntegerChain("shape", "shape"),
    fieldIntegerChain("color", "color"),
    fieldIntegerChain("company", "company_id"),
    fieldStringNotReqChain("Status", "status"),
    fieldFloatNotReqChain("Table value", "table_value"),
    fieldFloatNotReqChain("Depth value", "depth_value"),
    fieldFloatNotReqChain("measurement height", "measurement_height"),
    fieldFloatNotReqChain("measurement width", "measurement_width"),
    fieldFloatNotReqChain("measurement depth", "measurement_depth"),
    fieldStringNotReqChain("Local Location", "local_location"),
    fieldStringNotReqChain("video", "video"),
    fieldStringNotReqChain("image", "image"),
    fieldStringNotReqChain("certificate", "certificate"),
    fieldStringNotReqChain("ratio", "ratio"),
    fieldStringNotReqChain("User comments", "user_comments"),
    fieldStringNotReqChain("Admin comments", "admin_comments"),
    fieldIntegerNotReqChain("quantity", "quantity"),
    fieldIntegerNotReqChain("color_intensity", "color_intensity"),
    fieldIntegerNotReqChain("clarity", "clarity"),
    fieldIntegerNotReqChain("lab", "lab"),
    fieldIntegerNotReqChain("report", "report"),
    fieldIntegerNotReqChain("polish", "polish"),
    fieldIntegerNotReqChain("symmetry", "symmetry"),
    fieldIntegerNotReqChain("fluorescence", "fluorescence"),
]